### ISSUE TITLE
runtime ERROR when compiling ingroup_inds

### ISSUE THREAD

**Issue by tyutlk** [Haiyang-W/DSVT#33]
when compling pcdet.ops.ingroup_inds added in this pull request, i met a runtime ERROR. and i could compile Openpcdet successfully.

Traceback (most recent call last):
  File "setup.py", line 133, in <module>
    'src/ingroup_inds_kernel.cu',
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File ".local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File .local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 668, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1578, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by chenshi3** [comment]
Could you provide cuda and pytorch version?

**Comment by tyutlk** [comment]
> Thanks for your fast reply, here is my config.
torch version:1.13.1+cu117
cuda version:11.7

BTW,maybe changing cuda version and pytorch could solve this problem ,but it could get more issue after merging this repo to Openpcdet.

**Comment by Haiyang-W** [comment]
please refer this [issue](please refer this [issue](https://github.com/Haiyang-W/DSVT/issues/16#issue-1670488520).). We will reproduce this issue and fix it later.

**Comment by chenshi3** [comment]
Could you provide ninja version?

**Comment by chenshi3** [comment]
> > Thanks for your fast reply, here is my config.
> > torch version:1.13.1+cu117
> > cuda version:11.7
> 
> BTW,maybe changing cuda version and pytorch could solve this problem ,but it could get more issue after merging this repo to Openpcdet.

I install cu117, torch1.13.1 and ninja1.11.1, and I can not reproduce this issue. Could you provide additional details?

**Comment by tyutlk** [comment]
the ninja version is 1.11.1 as same as u ,and the environment mentioned is on a slurm cluster machine, i've tried several times  and now i don't know what occurs this error. fine ,even so ,thanks much for ur fast reply !

**Comment by Haiyang-W** [comment]
> the ninja version is 1.11.1 as same as u ,and the environment mentioned is on a slurm cluster machine, i've tried several times and now i don't know what occurs this error. fine ,even so ,thanks much for ur fast reply !

The bug has been fixed in [here](https://github.com/Haiyang-W/DSVT/blob/99fac452bbe5600f8c19db25b51d98d9b74d259f/pcdet/ops/ingroup_inds/src/ingroup_inds_kernel.cu#L6). It's caused by ninja and torch extension.
